# fly.toml app configuration file generated for brightideas on 2025-03-28T23:45:34+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brightideas'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"
[build.args]
  NODE_ENV = "production"
[env]
  PORT = "3000" 
  HOST_ENV = "production" 
  WEBAPP_URL = "https://brightideas.fly.dev" 
[deploy]
  release_command = "pnpm --filter @brightideas/backend run pmp" 
[[services]]
  protocol = "tcp"
  internal_port = 3000 # Порт, который слушает твой backend (из [env].PORT)
  processes = ["app"] # соответствует процессу по умолчанию

  [[services.ports]]
    port = 80 # HTTP
    handlers = ["http"]
    force_https = true # Автоматически перенаправлять HTTP на HTTPS

  [[services.ports]]
    port = 443 # HTTPS
    handlers = ["tls", "http"]

  # Health Checks - проверки работоспособности твоего приложения
  # Замени /healthz на реальный эндпоинт, если он есть, или оставь TCP-проверку
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
