packages:
  - backend
  - webapp
  - shared
packageExtensions:
  '@typescript-eslint/eslint-plugin@*':
    peerDependencies:
      eslint: '*'
  'eslint-plugin-react-hooks@*':
    peerDependencies:
      eslint: '*'
